# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9f5d415a1781897b65ae69b11cda72a9617bba7ec88c75c7db972f134251513c44cbb0881da0f2ba318eec41e221fda67dbdddad34b3f707dfeabb73c291c1b

test:
  secret_key_base: 7a718930bf8479d5e605bfc4456e426584bd3477b9d5e0aa8e11d94ed45d2cab5564f8f9bd3c37a4964622b43f669dc2a81e8ad0c50c87f36b82ae451dd37b19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
